-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 09:44:41 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oop20191
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oop20191
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oop20191` DEFAULT CHARACTER SET utf8 ;
USE `oop20191` ;

-- -----------------------------------------------------
-- Table `oop20191`.`Khach_hang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop20191`.`Khach_hang` (
  `MaKH` VARCHAR(20) NOT NULL DEFAULT '',
  `TenKH` VARCHAR(45) NOT NULL DEFAULT '',
  `DiaChi` VARCHAR(45) NOT NULL DEFAULT '',
  `SDT` VARCHAR(10) NOT NULL DEFAULT '',
  `SoCMND` VARCHAR(15) NOT NULL DEFAULT '',
  `ThuDienTu` VARCHAR(45) NULL DEFAULT '',
  PRIMARY KEY (`MaKH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oop20191`.`Xe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop20191`.`Xe` (
  `Bienso` VARCHAR(10) NOT NULL DEFAULT '',
  `Loaixe` VARCHAR(45) NOT NULL DEFAULT '',
  `Trongtai` VARCHAR(45) NULL DEFAULT '',
  PRIMARY KEY (`Bienso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oop20191`.`Hop_Dong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop20191`.`Hop_Dong` (
  `MaHD` VARCHAR(20) NOT NULL DEFAULT '',
  `Hinhthucthanhtoan` VARCHAR(45) NOT NULL DEFAULT '',
  `Thoigiangui` VARCHAR(45) NOT NULL DEFAULT '',
  `MaKH` VARCHAR(20) NULL DEFAULT '',
  `Bienso` VARCHAR(10) NULL DEFAULT '',
  PRIMARY KEY (`MaHD`),
  INDEX `fk_Hop_Dong_Khach_hang1_idx` (`MaKH` ASC),
  INDEX `fk_Hop_Dong_Xe1_idx` (`Bienso` ASC),
  CONSTRAINT `fk_Hop_Dong_Khach_hang`
    FOREIGN KEY (`MaKH`)
    REFERENCES `oop20191`.`Khach_hang` (`MaKH`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Hop_Dong_Xe`
    FOREIGN KEY (`Bienso`)
    REFERENCES `oop20191`.`Xe` (`Bienso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oop20191`.`Bang_gia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop20191`.`Bang_gia` (
  `MaBG` INT NOT NULL AUTO_INCREMENT,
  `Tien` INT NOT NULL DEFAULT 0,
  `ThoiGian` INT NOT NULL DEFAULT 0,
  `Loaixe` VARCHAR(45) NOT NULL DEFAULT '',
  `Loaive` VARCHAR(45) NOT NULL DEFAULT 'Tháng',
  PRIMARY KEY (`MaBG`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
