-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 21:54:25 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oop20191
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oop20191
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oop20191` DEFAULT CHARACTER SET utf8 ;
USE `oop20191` ;

-- -----------------------------------------------------
-- Table `oop20191`.`Khach_hang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop20191`.`Khach_hang` (
  `MaKH` VARCHAR(10) NOT NULL,
  `TenKH` VARCHAR(45) NOT NULL,
  `DiaChi` VARCHAR(45) NOT NULL,
  `SDT` VARCHAR(45) NOT NULL,
  `SoCMND` VARCHAR(45) NOT NULL,
  `ThuDienTu` VARCHAR(45) NULL,
  PRIMARY KEY (`MaKH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oop20191`.`Bang_gia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop20191`.`Bang_gia` (
  `Loaive` VARCHAR(5) NOT NULL,
  `Tien` INT NOT NULL,
  `ThoiGian` DATE NOT NULL,
  `Loaixe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Loaive`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oop20191`.`Xe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop20191`.`Xe` (
  `Bienso` VARCHAR(10) NOT NULL,
  `Loaive` VARCHAR(5) NOT NULL,
  `Trongtai` DOUBLE NULL,
  PRIMARY KEY (`Bienso`),
  INDEX `fk_Xe_Bang_gia_idx` (`Loaive` ASC),
  CONSTRAINT `fk_Xe_Bang_gia`
    FOREIGN KEY (`Loaive`)
    REFERENCES `oop20191`.`Bang_gia` (`Loaive`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oop20191`.`Hop_Dong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oop20191`.`Hop_Dong` (
  `MaHD` VARCHAR(10) NOT NULL,
  `Hinhthucthanhtoan` VARCHAR(45) NOT NULL,
  `Thoigiangui` INT NOT NULL,
  `MaKH` VARCHAR(10) NOT NULL,
  `Bienso` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`MaHD`),
  INDEX `fk_Hop_Dong_Khach_hang_idx` (`MaKH` ASC),
  INDEX `fk_Hop_Dong_Xe1_idx` (`Bienso` ASC),
  CONSTRAINT `fk_Hop_Dong_Khach_hang`
    FOREIGN KEY (`MaKH`)
    REFERENCES `oop20191`.`Khach_hang` (`MaKH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hop_Dong_Xe`
    FOREIGN KEY (`Bienso`)
    REFERENCES `oop20191`.`Xe` (`Bienso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
